#!/usr/bin/env bash

usage() {
  cat <<'HELP'
Remove inactive lines; i.e., lines that are empty, whitespace-only, or comments.
Comments are where the first non-whitespace character/string is `#`, `//`, or `--`.
Example:

    cat /etc/hosts | active
HELP
}

for arg; do
  case $arg in
    -h|--help)
      usage
      exit 0
      ;;
  esac
done

# delete lines beginning with: #
# delete lines beginning with: //
# delete lines beginning with: --
# delete empty lines
sed \
-e '/^[[:blank:]]*#/d' \
-e '/^[[:blank:]]*\/\//d' \
-e '/^[[:blank:]]*--/d' \
-e '/^[[:blank:]]*$/d' \
"$@"
