#!/usr/bin/env python
import sys
import argparse

parser = argparse.ArgumentParser(description='Find all lines after the last occurrence in a file or STDIN.')
parser.add_argument('--last', action='store_true')
parser.add_argument('pattern')
parser.add_argument('files', nargs='*')
opts = parser.parse_args()

pattern = opts.pattern

if not sys.stdin.isatty():
    reader = sys.stdin
else:
    reader = (line for path in opts.files for line in open(path))

if opts.last:
    cache = []
    for line in reader:
        cache.append(line)
        if pattern in line:
            cache = []
    print ''.join(cache),
else:
    found = False
    for line in reader:
        if found:
            print line,
        if pattern in line:
            found = True

# how to do "until" (which is easier)
# after iteration --last | awk '/------/ { exit } { print }'
