#!/usr/bin/env python
import random
import argparse

parser = argparse.ArgumentParser(description='Generate random characters.')
parser.add_argument('--length', '-l', type=int, help='Length of each password', default=12)
parser.add_argument('--count', '-c', type=int, help='Number of passwords', default=1)
args = parser.parse_args()

ALPHADEC = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789'


def sample(population, k, replacement=False):
    if args.length > len(ALPHADEC):
        replacement = True
    if replacement is False:
        return random.sample(population, k)
    else:
        return sum((random.sample(population, 1) for _ in range(k)), [])

for i in range(args.count):
    print ''.join(sample(ALPHADEC, args.length))
