#!/usr/bin/env python
import random
import argparse

ALPHABET_CAPITALS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
ALPHABET_SMALL = 'abcdefghijklmnopqrstuvwxyz'
DIGITS = '0123456789'

POPULATIONS = {
    'all':         ALPHABET_CAPITALS + ALPHABET_SMALL + DIGITS,
    'alpha':       ALPHABET_CAPITALS + ALPHABET_SMALL,
    'uppercase':   ALPHABET_CAPITALS,
    'lowercase':   ALPHABET_SMALL,
    'digits':      DIGITS,
    'upperdigits': DIGITS + ALPHABET_CAPITALS,
    'lowerdigits': DIGITS + ALPHABET_SMALL,
    'upperhex':    DIGITS + 'ABCDEF',
    'lowerhex':    DIGITS + 'abcdef',
}


def main():
    parser = argparse.ArgumentParser(
        description='Generate random strings',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument('--length', '-l', type=int, default=16,
                        help='Length of each password')
    parser.add_argument('--count', '-c', type=int, default=1,
                        help='Number of passwords')
    parser.add_argument('--population', '-p', choices=POPULATIONS, default='all',
                        help='Population to sample from')
    opts = parser.parse_args()

    population = POPULATIONS[opts.population]
    k = opts.length

    for _ in range(opts.count):
        # random.choices does sampling with replacement
        print(''.join(random.choices(population, k=k)))

if __name__ == '__main__':
    main()
