#!/usr/bin/env python
import random
import argparse
import string

populations = dict(
    all=string.uppercase + string.lowercase + string.digits,
    alpha=string.uppercase + string.lowercase,
    uppercase=string.uppercase,
    lowercase=string.lowercase,
    digits=string.digits,
    upperdigits=string.digits + string.uppercase,
    lowerdigits=string.digits + string.lowercase,
    upperhex=string.digits + 'ABCDEF',
    lowerhex=string.digits + 'abcdef',
)


parser = argparse.ArgumentParser(description='Generate random strings',
    formatter_class=argparse.ArgumentDefaultsHelpFormatter)
parser.add_argument('--length', '-l', type=int, help='Length of each password', default=12)
parser.add_argument('--count', '-c', type=int, help='Number of passwords', default=1)

parser.add_argument('--population', '-p', choices=populations, help='Population to sample from', default='all')
opts = parser.parse_args()

pop = populations[opts.population]

for i in range(opts.count):
    # always sample with replacement
    print ''.join(pop[random.randrange(len(pop))] for _ in range(opts.length))
