#!/usr/bin/env python
import sys
import csv

print '''
    <style>
        table td {
            vertical-align: top;
            padding: 2px;
            border: 1px dotted #ddd;
            border-left: 0;
            border-top: 0;
        }
    </style>
'''

print '<table cellspacing="0" cellpadding="0">'

with open(sys.argv[-1], 'r') as input:
    csv_reader = csv.DictReader(input)

    fieldnames = csv_reader.fieldnames

    print '<tr>'
    for fieldname in fieldnames:
        print '<th>%s</th>' % fieldname
    print '</tr>'


    for record in csv_reader:
        print '<tr>'
        for fieldname in fieldnames:
            html = record[fieldname]
            if html:
                html = html.replace('\n', '<br/>')
            print '<td>%s</td>' % html
        print '</tr>'

print '</table>'
