#!/usr/bin/env bash

usage() {
  >&2 cat <<HELP
Usage: ... | drop [n]

Drop (delete) the first line (or n lines, if n is specified) of /dev/stdin.
HELP
}

n=1
while [[ $# -gt 0 ]]; do
  case $1 in
    -h|--help)
      usage
      exit 0
      ;;
    *)
      if [[ $1 =~ ^[0-9]+$ ]]; then
        n=$1
      else
        usage
        >&2 printf '\nNon-numeric command line arguments (%s) are not allowed\n' "$1"
        exit 1
      fi
      ;;
  esac
  shift
done

if [[ $n == 0 ]]; then
  usage
  >&2 printf '\nDropping 0 (zero) lines is called "cat".\n'
  exit 1
fi

sed "1,${n}d"
