#!/usr/bin/env bash
if [[ "${@---help}" =~ '--help' ]]; then
  >&2 cat <<EOS
Ghostscript (gs) wrapper with common defaults (NOPAUSE, BATCH, DEVICE=pdfwrite).
Appends -gs to the first argument's basename if no second argument is supplied.

    Example: fixpdf book.pdf [book-gs.pdf]
EOS
  exit 1
fi

OUTPUT="${2-${1/.pdf/-gs.pdf}}"
gs -q -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -sOutputFile=$OUTPUT -f $1
>&2 printf "fixpdf: wrote gs output to %s\n" "$OUTPUT"
