#!/usr/bin/env python
import sys
import argparse
from subprocess import Popen

parser = argparse.ArgumentParser(description='gs (ghostscript) wrapper',
    formatter_class=argparse.ArgumentDefaultsHelpFormatter)
parser.add_argument('input', help='input PDF')
parser.add_argument('output', nargs='?', help='output PDF (defaults to <input>-gs.pdf)')
# parser.add_argument('-v', '--verbose', action='store_true', help='print gs output')
opts = parser.parse_args()

input_path = opts.input
output_path = opts.output or input_path.replace('.pdf', '-gs.pdf')

args = ['gs', '-q', '-dNOPAUSE', '-dBATCH', '-sDEVICE=pdfwrite', '-sOutputFile=%s' % output_path, '-f', input_path]
print >> sys.stderr, ' '.join(args)

gs_process = Popen(args)
gs_process.wait()
