#!/usr/bin/env perl

# types of github links:
# 1. git@github.com:chbrown/scripts.git      (ssh)
# 2. git://github.com/chbrown/scripts.git    (git)
# 3. https://github.com/chbrown/scripts.git  (https)

open(GIT, "git remote --verbose |") || die "Failed: $!\n";
# basic `git remote -v` output:
# NAME PROTOCOLREPO (DIRECTION)
# $1           $2    $3
# (perl regex matches)
while (my $line = <GIT>) {
  if ($line =~ /^(\w+)\s+\S+?github\.com[:\/](.+?)(\.git)?\s+\(fetch\)$/) {
    my $url = "https://github.com/$2";
    print "$url\n";
    system("open", $url);
  }
}
