#!/usr/bin/env python
import argparse
from collections import Counter


def iter_counts(files):
    counter = Counter()
    for file in files:
        lines = (line.rstrip() for line in file)
        counter.update(set(lines))
    return counter


def main():
    parser = argparse.ArgumentParser(
        description='Find lines shared by all files.',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument('files', nargs='+', type=argparse.FileType('r'))
    opts = parser.parse_args()

    counter = iter_counts(opts.files)
    minimum = len(opts.files)
    for line, count in counter.items():
        if count >= minimum:
            print(line)


if __name__ == '__main__':
    exit(main())
