#!/usr/bin/env python
import argparse
from collections import Counter

parser = argparse.ArgumentParser(description='Find lines shared by all files.',
    formatter_class=argparse.ArgumentDefaultsHelpFormatter)
parser.add_argument('filenames', nargs='+')
opts = parser.parse_args()

total = Counter()

for filename in opts.filenames:
    with open(filename) as fp:
        lines = (line.rstrip() for line in fp)
        total.update(set(lines))

minimum = len(opts.filenames)

for line, count in total.iteritems():
    if count >= minimum:
        print line
