#!/usr/bin/env node
var stream = require('stream');
var util = require('util');

var streaming = require('streaming');

var optimist = require('optimist')
  .usage([
    "Usage: jsmap '$out = {id: $in.id}' <input.json >output.json",
    '',
    'Transform newline-separated JSON objects with JavaScript.',
    '',
    'Runs the code in the first command line argument for each line of input.',
    '* the object parsed from the JSON on stdin will be available as `$in`',
    '* $out defaults to `undefined`, which discards the current input',
    "* all other values of $out will be JSON.stringify'd and sent to stdout",
    '',
    "This script uses Node.js'/V8's vm functionality to sandbox the code.",
    '',
    'If you want to skip the vm and run code from a file, use jsed:',
    '  npm install -g jsed; jsed --help',
  ].join('\n'))
  .describe({
    init: 'code to run once',
    help: 'print this help message',
    verbose: 'print more output',
  })
  .boolean([
    'help',
    'verbose',
  ])
  .alias({
    init: 'i',
    help: 'h',
    verbose: 'v',
  });

var argv = optimist.argv;

if (argv.help) {
  optimist.showHelp();
}
else if (process.stdin.isTTY) {
  throw new Error('JSON must be piped in on STDIN');
}
else {
  argv = optimist.check(function(argv) {
    if (argv._.length < 1) {
      throw new Error('You must specify an eval string');
    }
    if (argv._.length > 1) {
      throw new Error('You must not specify more than one eval string');
    }
  }).argv;

  // 1. parser
  var parser = new streaming.json.Parser().on('error', function(err) {
    console.error('Failed to parse JSON input: %s', err.stack);
  });

  // 2. transform
  var code = argv._[0];
  var vm_stream = new streaming.VM(code, {}).on('error', function(err) {
    console.error('Failed to execute transform code: %s', err);
  });
  if (argv.init) {
    vm_stream.run(argv.init);
  }

  // 3. stringifier
  var stringifier = new streaming.json.Stringifier().on('error', function(err) {
    console.error('Failed to stringify output to JSON: %s', err);
  });

  process.stdin.pipe(parser).pipe(vm_stream).pipe(stringifier).pipe(process.stdout);
}
