#!/usr/bin/env node
const streaming = require('streaming')
const js_yaml = require('js-yaml')

const optimist = require('optimist')
.usage(`Usage: json2yaml < data.json

Convert a JSON file to YAML`)
.describe({
  help: 'print this help message',
})
.boolean(['help'])
.alias({help: 'h'})

const argv = optimist.argv

const convert = function(stream, callback) {
  streaming.readToEnd(stream, function(err, chunks) {
    const json = Buffer.concat(chunks)
    const obj = JSON.parse(json)
    const yaml = js_yaml.dump(obj)
    console.log(yaml)
    callback()
  })
}

if (argv.help) {
  optimist.showHelp()
}
else if (process.stdin.isTTY) {
  throw new Error('JSON must be piped in on STDIN')
}
else {
  convert(process.stdin, function(err) {
    if (err) throw err
  })
}
