#!/usr/bin/env python
import os
import sys
from datetime import datetime

# chardet is an external library (https://github.com/erikrose/chardet), available with `pip install chardet`
import chardet


def lsm(filename, out):
    with open(filename) as fd:
        raw = fd.read()
        guess = chardet.detect(raw)
        content = raw.decode(guess['encoding'])

    modified = datetime.fromtimestamp(os.path.getmtime(filename))
    print >> out, u'[%s] %s' % (modified.isoformat(' '), filename)
    print >> out, content.encode('utf8')


def main():
    import argparse
    parser = argparse.ArgumentParser(description='Consolidate list of text files into single document, converting to UTF-8 and recording filenames and "mtime" of the original file.')
    parser.add_argument('filenames', nargs='+', help='Files to read')
    opts = parser.parse_args()

    for filename in opts.filenames:
        lsm(filename, sys.stdout)

if __name__ == '__main__':
    main()
