#!/usr/bin/env python
import os
import sys
from datetime import datetime

for filepath in sys.argv[1:]:
    created = datetime.fromtimestamp(os.path.getmtime(filepath))
    content = open(filepath).read().decode('utf16')

    section = u'[{created}] {filepath}\n{content}\n\n'.format(
        created=created.isoformat(' '),
        filepath=filepath,
        content=content,
    )
    sys.stdout.write(section.encode('utf8'))
