#!/usr/bin/env python
import argparse
import hashlib


def md5sum_hexdigest(string):
    m = hashlib.md5()
    m.update(string.encode('utf-8'))
    return m.hexdigest()


def main():
    parser = argparse.ArgumentParser(
        description='Compute the MD5 hash of the command line arguments',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument('strings', nargs='*', help='Input strings')
    opts = parser.parse_args()

    for string in opts.strings:
        print(md5sum_hexdigest(string))


if __name__ == '__main__':
    exit(main())
