#!/usr/bin/env python
import argparse
import os
from subprocess import Popen, PIPE
from colorama import Fore  # , Back, Style

parser = argparse.ArgumentParser(description='mysqlimport + mysqlcreatedb')
parser.add_argument('database', help='MySQL database')
parser.add_argument('csv', help='CSV file to load')
parser.add_argument('-u', '--user', default=os.getlogin())
parser.add_argument('-t', '--table', help='Defaults to basename of "csv" argument')
parser.add_argument('-m', '--max-length', default=64, help='Maximum column name length')

opts = vars(parser.parse_args())
if not opts.get('table'):
    opts['table'] = os.path.basename(opts['csv'])

print 'Using options: ' + ' '.join('%s=%s' % kv for kv in opts.items())


def mysql(sql):
    print Fore.BLUE + sql + Fore.RESET

    proc_args = ['mysql', opts['database'], '-u', opts['user']]
    print Fore.YELLOW + '$ ' + ' '.join(proc_args) + Fore.RESET
    proc = Popen(proc_args, stdin=PIPE, stdout=PIPE, stderr=PIPE)
    stdout, stderr = proc.communicate(sql)

    if stdout:
        print Fore.GREEN + stdout + Fore.RESET
    if stderr:
        print Fore.RED + stderr + Fore.RESET


header = open(opts['csv']).next()

# VARCHAR(1024)
columns = ['`pkid` int(11) NOT NULL auto_increment', 'PRIMARY KEY (pkid)']
columns += ['`%s` TEXT' % col.strip()[:opts['max_length']] for col in header.split(',') if col != 'pkid']
opts['columns'] = ',\n'.join(columns)


create_table_sql = 'DROP TABLE IF EXISTS `{table}`; CREATE TABLE `{table}` (\n{columns});'.format(**opts)
mysql(create_table_sql)

# newline can be either escaped or literal, below. makes no difference to mysql, as far as I can tell.
load_data_sql = "LOAD DATA LOCAL INFILE '{csv}' INTO TABLE `{table}` FIELDS TERMINATED BY ',' ENCLOSED BY '\"' LINES TERMINATED BY '\\n';".format(**opts)
mysql(load_data_sql)
