#!/usr/bin/env bash
if [[ "${@---help}" =~ '--help' ]]; then
  >&2 cat <<HELP
Usage: openssl-showcerts serverfault.com

Use openssl to retrieve and show the certificates for the given server.
HELP
  exit 1
fi

# Thanks, https://serverfault.com/a/661982
# openssl expects to hear EOF from stdin to signal it to quit; else it'll just hang
: | openssl s_client -showcerts -servername $1 -connect $1:443 2>/dev/null |\
    openssl x509 -inform pem -noout -text
