#!/usr/bin/env python
import sys
import argparse

parser = argparse.ArgumentParser(description='Like col, but better.')
parser.add_argument('--separator', '-s', type=str, default=',')
parser.add_argument('--gutter', '-g', type=int, default=2)
opts = parser.parse_args()

# simply run `pcol -s \\t` to use a different character
separator = opts.separator.replace('\\t', '\t').replace('\\n', '\n')

widths = []
for raw_line in sys.stdin:
    line = raw_line.strip('\0').strip()
    vals = line.split(separator)
    if len(vals) > len(widths):
        widths = [0] * len(vals)

    widths = [max(len(val) + opts.gutter, width) for val, width in zip(vals, widths)]
    metaformat = '%%%ds' * len(widths)
    format = metaformat % tuple(widths)
    try:
        print format % tuple(vals)
    except IOError:
        # pipe's been closed, i.e. head'ed or tail'ed
        break
