#!/usr/bin/env bash
if [[ "${@---help}" =~ '--help' ]]; then
  >&2 cat <<HELP
Run pdfcrop on each argument, with meager (but non-zero) margins,
using pdfcrop's default output naming scheme (append -crop to basename).
For example:

    $(basename "$0") paper.pdf appendices-*.pdf
HELP
  exit 1
fi

for FILE in "$@"; do
  pdfcrop --margins 2 --clip "$FILE"
done
