#!/usr/bin/env bash
if [[ "${@---help}" =~ '--help' ]]; then
  cat <<EOS
Run the supplied arguments (PDFs) through Ghostscript (gs) and output a
single PDF with the same name as the first argument but with .gs appended
to the basename.

    Example: pdfcat chap1.pdf chap2.pdf chap2.pdf
EOS
  exit 1
fi

OUTPUT="${1%.pdf}.gs.pdf"

# The -o option implies the -dBATCH and -dNOPAUSE options.
gs -q -sDEVICE=pdfwrite -o "$OUTPUT" "$@"

printf "pdfcat: read %d PDFs and wrote gs output to %s\n" $# "$OUTPUT"
