#!/usr/bin/env bash
if [[ "${@---help}" =~ '--help' ]]; then
  printf "Run pdfcrop on each argument, with meager (but non-zero) margins,\n"
  printf "using pdfcrop's default output naming scheme (append -crop to basename)\n\n"
  printf "  Example: pdfcropall paper.pdf appendices-*.pdf\n"
  exit 1
fi

for FILE in "$@"; do
  pdfcrop --margins 2 --clip "$FILE"
done
