#!/usr/bin/env sh
# sed version:
LANG=C
pdftk - output - uncompress | sed -e '/^.UTXA/d' | pdftk - output - compress
# clean out the UT library marker perl -p -e 's/\(UTXA[^)]+\)//g'
# for PDF in "$PDFS"; do
#   gs -q -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -sOutputFile=$2 -f $1
#   gs -q -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -sOutputFile="${1/.pdf/-gs.pdf}" -f "$1"
#   cat "$pdf" | pdftk - output - uncompress | perl -p -e 's/\(UTXA[^)]+\)//g' | pdftk - output "$pdf.clean.pdf" compress;
# done
