#!/usr/bin/env bash

if [[ "${@---help}" =~ '--help' ]]; then
  # if there are no arguments, this will default $@ to --help, so it works for all cases.
  echo "The first argument should be the name of a PostgreSQL database."
  echo "Writes to a .sql.bz2 file in the current directory"
  echo
  echo "  Example: pg_backup notes"
  exit 1
fi

DATABASE=$1
FILENAME="$(date +%Y%m%d)-$DATABASE.sql.bz2"

if [[ -e "$FILENAME" ]]; then
  # use a longer timestamp format if the date-only file already exists.
  FILENAME="$(date +%Y%m%dT%H%M%S)-$DATABASE.sql.bz2"
fi

echo "Dumping PostgreSQL database '$DATABASE' to '$FILENAME'"

# --clean: clean (drop) database objects before recreating
# --create: include commands to create database in dump
# --no-owner: skip restoration of object ownership
pg_dump --clean --create --no-owner "$DATABASE" | bzip2 > "$FILENAME"

if [[ ${PIPESTATUS[0]} != 0 ]]; then
  echo "Removing '$FILENAME' due to 'pg_dump' error"
  rm "$FILENAME"
fi
