#!/usr/bin/env bash
if [[ "$@" =~ '--help' ]]; then
  >&2 cat <<HELP
Usage: plprint Config.plist
       <Config.plist plprint

Convert a file in Apple's "property list format" into XML,
then pretty print with ppxml.
HELP
  exit 1
fi

plutil -convert xml1 -o - "${@--}" | ppxml
