#!/usr/bin/env python
import sys
import json
counter = 0
while 1:
    counter += 1
    try:
        line = sys.stdin.readline()
        if not line:
            raise EOFError
        print '-----------------------------------| %d |---------------------------------' % (counter, )
        print json.dumps(json.loads(line), sort_keys=True, indent=2)
    except ValueError:
        print 'broken'
        print line
    except KeyboardInterrupt:
        break
    except EOFError:
        break
