#!/usr/bin/env python
import sys
import codecs
import fileinput

# codecs.BOM = '\xff\xfe'
# codecs.BOM_UTF8 = '\xef\xbb\xbf'
sys.stdout.write(codecs.BOM_UTF8)
for line in fileinput.input():
    print sys.stdout.write(line)
