#!/usr/bin/env python
#soundcloud music downloader by http://360percents.com - v3.0 on Nov 1st 2011
#Author: Luka Pusic <pusic93@gmail.com>
#Python: Chris Brown <io@henrian.com>
import re
import argparse
import requests

parser = argparse.ArgumentParser(description='Soundcloud downloader')
parser.add_argument('urls', nargs='+', help='Url(s) to page with links')
args = parser.parse_args()

headers = {'user-agent': 'Mozilla/5.0'}

def download_stream(stream, title):
    unicode_title = title.decode('unicode-escape')
    r = requests.get(stream, headers=headers)
    mp3 = '%s.mp3' % unicode_title
    print 'Downloading %s' % mp3
    with open(mp3, 'wb') as fp:
        fp.write(r.content)

def download_url(url):
    r = requests.get(url, headers=headers)
    # lines = r.text
    # for line in lines.split('\n'):
        # if 'track?' in line and 'page=' in line:
            # awk -F= '{print $NF}' | sort -nu | tail -n 1`
    pages = 1
    for page in range(pages):
        page_url = '%s?page=%d' % (url, page) if page != 0 else url
        r = requests.get(page_url, headers=headers)
        streams = re.findall(r'"(http://media.soundcloud.com/stream/\w+\?stream_token=\w+)"', r.text)
        titles = re.findall(r'"title"\s*:\s*"([^"]+)"', r.text)
        for stream, title in zip(streams, titles):
            download_stream(stream, title)

for url in args.urls:
    download_url(url)
