#!/usr/bin/env python
import sys
from time import time

started = time()

sys.stdout.write('Press \\n to end.')
sys.stdout.flush()

STDOUT = sys.stdout
with open('/dev/null', 'w') as DEVNULL:
    sys.stdout = DEVNULL
    sys.stdin.read(1)
sys.stdout = STDOUT

ended = time()

duration = ended - started

print('\r{:0.4f}s'.format(duration))
