#!/usr/bin/env python
import os
import shutil

import logging
logger = logging.getLogger('style')


def walk(root):
    # flatten into just all the full filepaths
    for dirpath, _dirnames, filenames in os.walk(root):
        for filename in filenames:
            yield os.path.join(dirpath, filename)


def walkall(roots):
    for root in roots:
        if os.path.isdir(root):
            for filepath in walk(root):
                yield filepath
        else:
            yield root


def seek_to_beginning_of_final_whitespace(fp, max_offset=None):
    # jump to EOF
    fp.seek(0, 2)
    if max_offset is None:
        max_offset = fp.tell()
    # find location of last non-whitespace character by starting at the end and working backward
    for offset in range(1, max_offset + 1):
        # if the second argument of seek (whence) is 2,
        #   the first argument (offset) is evaluated relative to the end of the file
        fp.seek(-offset, 2)
        char = fp.read(1)
        if not char.isspace():
            # we just read over the last non-whitespace character, so the
            # current file position is now at the first of the final whitespace
            break
    else:
        # the else: after a for: loop is executed only if the for loop runs to exhaustion (no break)
        # if we seek all the way to the beginning without finding a single non-whitespace character,
        # then there are none, and we should set the file position to the very top of the file
        fp.seek(0)
    # logger.debug('Set file position to %d, last read %r', fp.tell(), char)


def ivars(obj, private=False):
    for name, value in vars(obj).items():
        if private or not name.startswith('_'):
            yield name, value


class MethodRunner(object):
    @classmethod
    def __run__(cls, arg):
        for method_name, method_callable in ivars(cls):
            result = method_callable(arg)
            logger.debug('%s.%s(%s) => %s', cls.__name__, method_name, arg, result)
            yield method_name, result


class Test(MethodRunner):
    '''
    Each Test.method returns a truthy value,
    for example, the number of errors (a positive integer), or True,
    if the given file violates the test.
    '''
    def trailing_whitespace(filepath):
        errors = 0
        with open(filepath) as fp:
            for lineno, line in enumerate(fp, 1):
                if line.rstrip('\n').endswith((' ', '\t')):
                    errors += 1
                    logger.warning('%s:%d: trailing whitespace', filepath, lineno)

        return errors

    def single_newline_at_eof(filepath):
        with open(filepath) as fp:
            seek_to_beginning_of_final_whitespace(fp)
            # fp is now sitting at the beginning of the final whitespace, if any, in the file.
            #   if there is none, fp.tell() == size
            # the rest of the file should be a single newline:
            return fp.read() != '\n'

    # @classmethod
    # def __run__extra(cls, arg):
    #     failed = method(filepath)
    #     if failed:
    #         logger.error('%s failed %s test', filepath, check)
    #     else:
    #         logger.debug('%s passed %s test', filepath, check)


class Fix(MethodRunner):
    def trailing_whitespace(filepath):
        # use a temporary file so we don't lose anything if it breaks
        filepath_tmp = filepath + '.tmp'
        with open(filepath, 'r') as file_in, open(filepath_tmp, 'w') as file_out:
            for line in file_in:
                file_out.write(line.rstrip() + '\n')
        # copy metadata from the original before we write over it
        shutil.copystat(filepath, filepath_tmp)
        # and a simple rename to finalize the changes
        os.rename(filepath_tmp, filepath)

    def single_newline_at_eof(filepath):
        # much the same as
        with open(filepath, 'a+') as fp:
            seek_to_beginning_of_final_whitespace(fp)
            # truncate first, since write will otherwise trigger jumping to the end of the file
            # from the file.truncate documentation:
            #   Size defaults to the current file position, as returned by tell()
            fp.truncate()
            fp.write('\n')


def main():
    import argparse
    parser = argparse.ArgumentParser(
        description='Test or apply styles',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument('files', nargs='*', default=['.'],
                        help='Files / directories to read')
    parser.add_argument('-f', '--fix', action='store_true',
                        help='Fix files that fail tests (potentially destructive, be careful!)')
    parser.add_argument('-v', '--verbose', action='store_true',
                        help='Print extra information')
    parser.add_argument('-q', '--quiet', action='store_true',
                        help='Print less information (overrides --verbose)')
    # parser.add_argument('-a', '--auto', action='store_true',
    #                     help='Ignore files in .gitignore, etc.')
    opts = parser.parse_args()

    # DEBUG=10, WARN=30, ERROR=40
    level = logging.WARN
    if opts.verbose:
        level = logging.DEBUG
    if opts.quiet:
        # quiet trumps verbose
        level = logging.ERROR
    logging.basicConfig(format='%(levelname)-8s %(message)s', level=level)

    for filepath in walkall(opts.files):
        for method_name, test_result in Test.__run__(filepath):
            if test_result:
                logger.error('TEST[%s] %r: %s', method_name, filepath, test_result)

        # just fix everything, actually
        if opts.fix:
            for method_name, fix_result in Fix.__run__(filepath):
                if fix_result:
                    logger.debug('FIX[%s] %r: %s', method_name, filepath, fix_result)


if __name__ == '__main__':
    main()
