#!/usr/bin/env python
import sys
import ujson
while True:
    try:
        line = sys.stdin.readline()
        if not line:
            raise EOFError
        doc = ujson.decode(line)
        text = doc.get('text', None)
        if text is not None:
            sys.stdout.write(text + '\n')
    except (KeyboardInterrupt, EOFError):
        break
    except Exception: # e.g. ValueError
        continue
