#!/usr/bin/env bash
# Use like: tgz penn-treebank-rel3/

# remove trailing slash (hopefully there's only one)
file=${1%/}
[ ! -e $file ] && echo $file does not exist. && exit 1

file_tar_gz=$file.tar.gz
[ -e $file_tar_gz ] && echo $file_tar_gz already exists, not overwriting. && exit 1

echo tar -czf $file_tar_gz $file
tar -czf $file_tar_gz $file
mv $file $file.tmp
echo $file_tar_gz created and original moved to $file.tmp
