#!/usr/bin/env bash

set -e # exit on first command that fails

usage() {
  >&2 cat <<HELP
Usage: $(basename "$0") [filepath [...]]

List the total sizes of the specified directory's children nodes,
in Megabytes, sorted from smallest to largest.
HELP
}

FILES=()
while [[ $# -gt 0 ]]; do
  case $1 in
    -v|--verbose)
      >&2 printf 'Entering debug (verbose) mode.\n'
      set -x
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      # check that the given filepath exists
      if [[ ! -e $1 ]]; then
        >&2 printf '"%s" does not exist.\n' "$1"
        exit 1
      fi
      # add to the list of files, trimming trailing slashes
      FILES+=("${1%/}")
      ;;
  esac
  shift
done

# du:
#   -m   Display sizes in units of 1 Mbyte (1048576 bytes)
#   -d 1 Recurse down into children, but no further
# sort:
#   -g   Compare numerically rather than lexicographically
du -m -d 1 "${FILES[@]}" \
| sort -g
