#!/usr/bin/env node
/*jslint node: true */
var fs = require('fs');
var logger = require('loge');
var sqlcmd = require('sqlcmd');
var Insert = require('sqlcmd/commands/insert').Insert;
var streaming = require('streaming');
var yaml = require('js-yaml');

var optimist = require('optimist')
  .usage([
    'Usage: yaml2sql < tabular_data.yaml',
    '',
    'Convert a yaml file to SQL INSERT statements',
    '',
    'This is handy if you have a yaml file with table names as keys, where',
    "each table's value is a list of objects, where those objects are rows",
    'to be inserted into that table. This lets you run something like:',
    '    <my_data.yaml yaml2sql | psql my_database',
  ].join('\n'))
  .describe({
    help: 'print this help message',
    verbose: 'print more output',
  })
  .boolean(['help', 'verbose'])
  .alias({verbose: 'v'});

var argv = optimist.argv;
logger.level = argv.verbose ? 'debug' : 'info';

var convert = function(stream, callback) {
  streaming.readToEnd(stream, function(err, chunks) {
    var text = Buffer.concat(chunks);
    var data = yaml.load(text);
    var tables = Object.keys(data);
    tables.forEach(function(table) {
      console.log('-- TABLE: %s', table);

      var rows = data[table];
      rows.forEach(function(row) {
        var sql = new Insert(table).set(row).toUnsafeSQL().replace(/\s+RETURNING \*/, ';');

        console.log(sql);
      });
    });
  });
};

if (argv.help) {
  optimist.showHelp();
}
else if (process.stdin.isTTY) {
  throw new Error('YAML must be piped in on STDIN');
}
else {
  convert(process.stdin, function(err) {
    if (err) throw err;
  });
}
