#!/usr/bin/env node
/*jslint node: true */
var fs = require('fs');
var streaming = require('streaming');
var js_yaml = require('js-yaml');

var optimist = require('optimist')
  .usage([
    'Usage: yaml2json < data.yaml',
    '',
    'Convert YAML file to JSON',
  ].join('\n'))
  .describe({help: 'print this help message'})
  .boolean('help');

var argv = optimist.argv;

if (argv.help) {
  optimist.showHelp();
}
else if (process.stdin.isTTY) {
  throw new Error('YAML must be piped in on STDIN');
}
else {
  streaming.readToEnd(process.stdin, function(err, chunks) {
    if (err) throw err;
    var yaml = Buffer.concat(chunks);
    var obj = js_yaml.safeLoad(yaml);
    var json = JSON.stringify(obj);
    console.log(json);
  });
}
